version:     "0001--11-Feb-2022"
copyright:   "2022"
author:      "Jesika Avonia"
title:       "OS221: Operating Systems 2021-2"
githublink:  "https://github.com/jesikaavonia/os221/"
myloglink:   "TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
